# Generated by Django 2.2.2 on 2019-07-04 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='age',
            field=models.PositiveIntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='agender',
            field=models.CharField(choices=[('0', '男'), ('1', '女')], max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='aid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='aname',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.ImageField(default='', upload_to='actors/', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuapp.Actor', verbose_name='演员'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='m_pub_date',
            field=models.DateField(verbose_name='上映日期'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='mcomment',
            field=models.TextField(verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='mimage',
            field=models.ImageField(null=True, upload_to='movies/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='mname',
            field=models.CharField(max_length=30, verbose_name='影片名称'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='mread',
            field=models.PositiveIntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
